### ISSUE TITLE
Project status behavior is not as expected

### ISSUE THREAD

**Issue by DavidKoot** [TAUSBV/dqf-api#102]
Right now it seems to be possible to have a leaf project that is in progress, while its parent projects are completed. QD shows 'completed for the owner of the master project, or any of the parent projects.
How does the current logic work, and check if it makes sense.

(email 2017-09-01, Mateusz, XTM)
> Hello David,
> 
> thank you for your response. The reason why I am asking this question is that when I completed both projects and then I have called the method to add complete translation to the second of the projects, the status in the dashboard didn't change to "in progress". I have checked using API, that the status of the first project (id: 40508) is still completed, but the status of the second project (id: 40509) is "inprogress". So the information in the dashboard, that the project is completed seems to be a little bit misleading as actually the project is in progress. Is it also an expected behavior, or this could be changed?
> 
> Kind regards,
> Mateusz
>

**Comment by DavidKoot** [comment]
A more extensive description is here:
https://github.com/TAUSBV/quality-dashboard/issues/154

**Comment by DavidKoot** [comment]
A more extensive description is here:
https://github.com/TAUSBV/quality-dashboard/issues/154

**Comment by dacedzeguze** [comment]
Will be addressed in the QD repository, closing this one.
