### ISSUE TITLE
DQF supports one file(file_name) per task

### ISSUE THREAD

**Issue by nikosarg** [TAUSBV/dqf-api#11]
The current structure of DQF doesn't allow multiple files to be uploaded for a single task(language pair).
Each language pair has it's own file in a project.
Using the API the translators can have multiple files to translate for one language pair. Only the first file name for a task will be stored in DQF.

**Comment by Impertatore** [comment]
I have just noticed this issue now as well; it initially threw me off with the understanding the API integration.

Reproduce:
Upload segments from multiple files for a single language.  The segments from all files are uploaded, but there is no distinction from which file they are derived -> specifically.  Only the name of the first file is displayed.

This will be a very common implementation requirement to be able to distinguish file versus segment.

**Comment by gorogattila** [comment]
We will start working on this in the API trying to have this ready in v1.0. If this breaks something in DQF this means we will need more time since will have to change DQF first to support multiple file upload.

**Comment by achimr** [comment]
Need to investigate how each integrator structures their projects/files. Typical is multiple files per project and multiple target languages per project.

**Comment by pvalli** [comment]
We have an Asana task about this feature request: https://app.asana.com/0/79536541830952/79629614889071/f
