### ISSUE TITLE
POSTing new productivity project returns HTTP 404

### ISSUE THREAD

**Issue by achimr** [TAUSBV/dqf-api#12]
When I send a HTTP POST request to
http://dqf.ta-us.net/api/v1/productivityProject/
With the header:
DQF_PMANAGER_KEY my key
and form content in application/x-www-form-urlencoded with the following parameters
name: Achim REST created project
quality_level: 1
process: 1
source_language: en-US
contentType: 1
industry: 1

I get an HTTP 404 error returned from the server.

Expected: The project created and the project info returned in a JSON response body

**Comment by pvalli** [comment]
@achimr is this issue resolved? Thanks.
