### ISSUE TITLE
No spamming protections in translator generation

### ISSUE THREAD

**Issue by achimr** [TAUSBV/dqf-api#16]
POST request to http://dqf.ta-us.net/api/v1/translator?name=Foo%20Bar&email=foobar@example.com

An email gets sent to foobar@example.com

I could do this 100,000 times to send 100,000 emails to this person.

**Comment by achimr** [comment]
Related to #57

**Comment by achimr** [comment]
Requiring a valid DQF_PROJECT_KEY in the header would still allow translators (or really anybody who gets hold of a valid project key) to spam anybody.

In my opinion we should deprecate translator key generation via the API and add web UI with CAPTCHA to sign up for translator keys. We can also provide translator key lookup/reset through the UI.

This is related to #54 and #57.

**Comment by achimr** [comment]
This is also connected to the question whether translator users should get a taus.net account in an advanced user management. Then translator account management in DQF could be phased out. Move to a later version than v1.1?

**Comment by nikosarg** [comment]
I agree that this should be moved on a later version.

**Comment by pvalli** [comment]
This is a Security feature that has been moved to Asana: https://app.asana.com/0/78315545221439/81343959392943
