### ISSUE TITLE
Large post-editing time doesn't generate reports

### ISSUE THREAD

**Issue by nikosarg** [TAUSBV/dqf-api#18]
Testing the API some large post-editing times were submitted. (1432140000)
The report cannot be generated when that happens!

**Comment by achimr** [comment]
Somewhat related issue #36

**Comment by pvalli** [comment]
Is this still the case? I had very large productivity time and still had a report in the QD. Remember @nikos?

**Comment by nikosarg** [comment]
The post-editing time which caused this issue was extremely high(1432140000 ms ≈ 16 days).
In your case @pvalli there were really low and really high pe times but not something like that.

We could investigate and see if this issue still persists and which are our limits. 
In our average productivity reports we exclude pe time less than 0.5 secs and more than 10 minutes.
