### ISSUE TITLE
change translator from an existing task

### ISSUE THREAD

**Issue by antoniofarina** [TAUSBV/dqf-api#19]
MateCAT cannot separate the step of create a project from the step of create a task. 
Moreover, at the time of the project creation, MateCAT is not aware of the translator to which the single task will be assigned.
Currently, we are assigning all the tasks to the same translator.
It could be useful to have an API that allows to change the translator key associated to an existing task.

From the MateCAT point of view, this is the most versatile way to achieve the goal of assign a translator to a task in MateCAT: we could allow the translator itself to add his own key, or we could assign this grant to the project owner (I mean the owner of the project manager key).

**Comment by achimr** [comment]
We should fix this by also allowing a DQF_PMANAGER_KEY for authorizing a POST request to /productivityProject/{projectid}/task
In this case an additional parameter `translator_id` needs to be added and is required.
If a translator (authorized via DQF_TRANSLATOR_KEY) creates a task including the optional `translator_id` it should be verified if the translator id matches the identifier of this translator. If it doesn't match the task should not be created and error be returned.

**Comment by achimr** [comment]
To enable changing the translator for an existing task we should add a PUT method to
/productivityProject/{projectid}/task/{taskid}
The parameters need to be the same set as the one allowed for the POST method to
/productivityProject/{projectid}/task
to create a task.

**Comment by achimr** [comment]
Nikos to make change to require either DQF_TRANSLATOR_KEY or DQF_PMANAGER_KEY

**Comment by nikosarg** [comment]
A PUT method to /productivityProject/{projectid}/task/{taskid}/translator will be added to update the translator of a task.

**Comment by achimr** [comment]
Verified the following via the UI on the test server:
* Task creation by project manager
* Translator reassignment by project manager (via put request to /api/v1/productivityProject/{project_id}/task/{task_id}/translator)
