### ISSUE TITLE
Internal server error - add reason

### ISSUE THREAD

**Issue by HenkBoxma** [TAUSBV/dqf-api#2]
Please return the reason why the error occured. This can be a technical one, e.g. that a certain key already exists...
If possible, do not return an error.

**Comment by gorogattila** [comment]
We are sending specific error message. Needs more testing in the plug-in why these messages are not shown.

**Comment by HenkBoxma** [comment]
Added all information in one dialog. User gets a message that he can copy the information and send it to TAUS.
![image](https://cloud.githubusercontent.com/assets/11646718/9692102/1c2e90e4-5347-11e5-9a02-a27eb2afcd20.png)

Resized:

![image](https://cloud.githubusercontent.com/assets/11646718/9692113/2c3f8286-5347-11e5-9f66-984c5ce4efb3.png)

**Comment by HenkBoxma** [comment]
@pvalli : please test

**Comment by pvalli** [comment]
Yes. I get one error window without tabs. Good info message.
