### ISSUE TITLE
Creating a new task for project resets the status of project from "Active" to "Initializing"

### ISSUE THREAD

**Issue by achimr** [TAUSBV/dqf-api#21]
1. Log on to DQF (test server) and note project manager key
2. Create new project by HTTP POST to the following URL
http://dqf.ta-us.net/api/v1/productivityProject?name=Achim+REST+created+project&quality_level=1&process=2&source_language=en-US&contentType=1&industry=1
and providing the project manager key in the DQF_PMANAGER_KEY header. Note the project id and project key on successful response
3. Create or retrieve translator account by HTTP POST to the following URL: http://dqf.ta-us.net/api/v1/translator?name=Achim%20Ruopp&email=achim@taus.net
4. Create a new task by HTTP POST to the following URL:
http://dqf.ta-us.net/api/v1/productivityProject/%lt;project_id>/task?target_language=de-DE&file_name=foobar
while providing the translator key as DQF_TRANSLATOR_KEY and the project key as DQF_PROJECT_KEY in the HTTP header
Note the task_id returned in the HTTP response header
5. Create new segment by HTTP POST to
http://dqf.ta-us.net/api/v1/productivityProject/&lt;project_id>/task/0/segment?source_segment=My%20source%20text&target_segment=Some%20MT&new_target_segment=Mein%20Quelltext&time=12345&cattool=1&tm_match=0&mtengine=1&mt_engine_version=567
while providing the translator key as DQF_TRANSLATOR_KEY and the project key as DQF_PROJECT_KEY in the HTTP header
Note the newly created segment_id returned in the HTTP response header.

Result:
When logging onto the DQF UI I can see the project in the project list. The  project status is "Active" and I can run reports on the project.

6. Create a new task by HTTP POST to the following URL:
http://dqf.ta-us.net/api/v1/productivityProject/%lt;project_id>/task?target_language=fr-FR&file_name=foobar2
while providing the translator key as DQF_TRANSLATOR_KEY and the project key as DQF_PROJECT_KEY in the HTTP header
Note the task_id returned in the HTTP response header

Result:
When refreshing the DQF UI, the status of the project switches from "Active" to "Initializing...". I can't generate reports anymore

7. Create new segment (in original task) by HTTP POST to
http://dqf.ta-us.net/api/v1/productivityProject/&lt;project_id>/task/0/segment?source_segment=My%20sourceeee%20text&target_segment=Some%20MT&new_target_segment=Mein%20Quelltext&time=12345&cattool=1&tm_match=0&mtengine=1&mt_engine_version=567
while providing the translator key as DQF_TRANSLATOR_KEY and the project key as DQF_PROJECT_KEY in the HTTP header
Note the newly created segment_id returned in the HTTP response header.

Result:
When refreshing the DQF UI, the status of the project switches from "Initializing..." to "Active". I can generate reports again. The two segments submitted are noted in the task statistics for the en-US_de-DE task, so apparently there is no data loss(?).

**Comment by nikosarg** [comment]
The Project status will become "Active" after the first segment of a task has been submitted, and it will remain "Active" even if more tasks are going to be created. 
The Reports will have a similar behaviour; stats will be shown only for tasks that segment data exists.
