### ISSUE TITLE
Creating a project package in Trados Studio deletes DQF meta-data from .sdlproj file

### ISSUE THREAD

**Issue by achimr** [TAUSBV/dqf-api#23]
Reported by Ryan: When creating a project package in Trados Studio, all DQF metadata is lost from the .sdlproj file. So when the PM sends a package to a translator, no data is returned to the DQF server as that translator works on the project.

**Comment by HenkBoxma** [comment]
This one should be fixed now. Awating for conformation from Steve and Ryan (LDS Church)

**Comment by HenkBoxma** [comment]
This is the same as issue  #35 for increment 1.0

**Comment by HenkBoxma** [comment]
Fixed. Root cause is the update of Studio to a newer version. In that new version the metadata was set to the clone. For details, see https://community.sdl.com/developers/language-developers/f/58/p/4347/16149#16149
