### ISSUE TITLE
For projects with more than one target language only one appears in the DQF report

### ISSUE THREAD

**Issue by achimr** [TAUSBV/dqf-api#24]
Reported by Ryan: If the project has more than one target language in it, only one appears in the DQF report. All translations in the project, no matter what language they are actually for, are grouped under this one language. It is not clear to me how the language is selected.

**Comment by HenkBoxma** [comment]
The task_id is assigned per TranslatorKey and ProjectKey. Only one translator can be registered per machine.
We store this taskId in the first segment of a file a metadata.
