### ISSUE TITLE
It is not possible to create segments with empty source/target/new target

### ISSUE THREAD

**Issue by achimr** [TAUSBV/dqf-api#25]
1. Create a project and task in a specific language pair with the API
2. Create a new segment by issuing HTTP POST to
http://dqf.ta-us.net/api/v1/productivityProject/&lt;project_id>/task/&lt;task_id>/segment?source_segment=fo&target_segment=fa&time=12345&new_target_segment=&cattool=1&tm_match=0&mtengine=1&mt_engine_version=567

Result: HTTP 405 method not allowed
```
{"code":405,"type":"method not allowed","message":"Required parameters are missing!"}
```

Or:

2. Create a new segment by issuing HTTP POST to
http://dqf.ta-us.net/api/v1/productivityProject/&lt;project_id>/task/&lt;task_id>/segment?source_segment=fo&target_segment=fa&time=12345&new_target_segment&cattool=1&tm_match=0&mtengine=1&mt_engine_version=567

Result: HTTP 405 method not allowed

Expected: HTTP 200, segment created with empty new target

Side note: 
http://dqf.ta-us.net/api/v1/productivityProject/&lt;project_id>/task/&lt;task_id>/segment?source_segment=fo&target_segment=fa&time=12345&new_target_segment=&cattool=1&tm_match=0&mtengine=1&mt_engine_version=567 (all non-empty values) works

**Comment by achimr** [comment]
For me not passing the parameter new_target_segment leads to a HTTP 500 error.

**Comment by HenkBoxma** [comment]
Can you define it as an optional parameter?

-Henk Boxma.
Sent from mobile (please excuse typos)

**Comment by nikosarg** [comment]
The new_target_segment will become possible to be empty on the next update.
The parameter should still be mentioned but the value can stay empty.
> /api/v1/productivityProject/project_id/task/task_id/segment?source_segment=testing the source&target_segment=test&new_target_segment&time=12321&tm_match=60&cattool=5&mtengine=6&mt_engine_version=V2

Shall the source_segment and the target_segment accept empty segments as well as the title of this issue specifies?
It doesn't make much sense to have the source_segment empty. 
The target_segment might be possible if there is no MT Engine specified, but then we should include it on the update segment(PUT) method which will complicate the process.

**Comment by HenkBoxma** [comment]
Do not forget to also specify this in the API, so that other developers use
this for other implementations of plugins.

Thanks,
Henk

**Comment by achimr** [comment]
Yes, I think source_segment and target_segment should accept empty strings as well (e.g. think of a situation where a developer is forced to add an empty text box to a UI to allow for text expansion in a translation - the source_segment in this case would be empty and then new_target_segment would be a string).

In general we should include all parameters in a PUT request that all included in a POST request in the REST API. Google for "rest http patch vs put" or see http://williamdurand.fr/2014/02/14/please-do-not-patch-like-an-idiot/ (ignoring the offensive title of the blog post)

BTW - I assume the source_segment in the URL you mention needs to be URL encoded?
api/v1/productivityProject/project_id/task/task_id/segment?source_segment=testing+the+source&target_segment=test&new_target_segment&time=12321&tm_match=60&cattool=5&mtengine=6&mt_engine_version=V2
or 
api/v1/productivityProject/project_id/task/task_id/segment?source_segment=testing%20the%20source&target_segment=test&new_target_segment&time=12321&tm_match=60&cattool=5&mtengine=6&mt_engine_version=V2

**Comment by gorogattila** [comment]
Hi, is this one solved? In the API specs the field is still "required".
