### ISSUE TITLE
Pausing the timer for every view except Editor

### ISSUE THREAD

**Issue by achimr** [TAUSBV/dqf-api#28]
Reported by Ryan: The “TAUS DQF Coffee break!” view seems to be the only way to pause the timer – shouldn’t the timer be paused for every view except the Editor? Also, shouldn’t the timer pause if you’re in the Editor view but you haven’t done anything for a while?

**Comment by HenkBoxma** [comment]
Fixed. The timer is now paused when the user leaves the editor, and restarted when he enters the editor again.
