### ISSUE TITLE
API function to remove segments for a specific document/task

### ISSUE THREAD

**Issue by Impertatore** [TAUSBV/dqf-api#29]
Include the possibility to remove segments that were uploaded for a specific document/task

This may arise if a version of the document changes are uploaded by mistake; It would be useful to include the possibility to correct this mistake by allowing the user to remove the incorrectly uploaded segments for a specific Task.... and then proceed with uploading the correct document changes.

**Comment by gorogattila** [comment]
Needs scoping out.

**Comment by pvalli** [comment]
This is a feature request that has been moved to Asana (https://app.asana.com/0/79629614889134/83034761351795). @Impertatore we will notify you when the feature becomes available. We are trying to use Github for issue tracking only.
