### ISSUE TITLE
List the task ids when GET project

### ISSUE THREAD

**Issue by Impertatore** [TAUSBV/dqf-api#31]
This would be useful for the author of the DQF project.  When the author queries the project, then they should recover the project attributes + the task ids.  From the documentation, I don’t see the task ids included in the response.

**Comment by achimr** [comment]
Best RESTful solution: HTTP GET to
/productivityProject/{projectid}/task/
Should retrieve an array of tasks for the project.
(see also http://programmers.stackexchange.com/questions/186959/trailing-slash-in-restful-api)

**Comment by Impertatore** [comment]
perfect
