### ISSUE TITLE
uploading segments with the entity &#39; throws a error from the service

### ISSUE THREAD

**Issue by Impertatore** [TAUSBV/dqf-api#33]
Noticed an issue when uploading segments with the entity &#39; for single quote.  the service returns HTTP status code 500.

**Comment by gorogattila** [comment]
Escape special characters.

**Comment by nikosarg** [comment]
Single quotes seem to work ok.
The issue occurs by the character "#" in the [html code](http://www.ascii.cl/htmlcodes.htm) for the single quote.
If these characters are converted using [url encoding](http://www.w3schools.com/tags/ref_urlencode.asp), then the segments can be uploaded without any issue.
Working example:
`/api/v1/productivityProject/1568/task/3703/segment?source_segment=source%20hash%20%23&target_segment=target%20single%20quote%20'&new_target_segment=new%20target%20percentage%20%25&time=1030&tm_match=45&cattool=3&mtengine=4&mt_engine_version=v2`

**Comment by Impertatore** [comment]
Hi All,
I confirm the findings from Nikos above, this issue is invoked when the # character is submitted with the segment.  This character in particular needs to URL encoded;  I’ll include this function to manage url_encode with the next update of the software.
Good work!
Patrick.

**Comment by Impertatore** [comment]
eventually use System.Web.HttpContext.Current.Server.UrlEncode

**Comment by Impertatore** [comment]
settled with using System.Uri.EscapeDataString(); seems to work better with individual chars

**Comment by Impertatore** [comment]
.
