### ISSUE TITLE
Only store project ID locally

### ISSUE THREAD

**Issue by HenkBoxma** [TAUSBV/dqf-api#37]
Steve suggests to only store the project key locally in the project and the rest on the server. It makes sense. In that case, we need an additional API call, so that the plugin retrieves the settings from the server and can display it. In general, I think that that is better than storing it locally. It would also allow someone to change the setting later on the server in case a mistake was made.

Steve's quote:

I have also been thinking more about a simple integration with WorldServer.  It seems that the main piece of information that must be added to the WorldServer project (in order to be sent in the packages to translators using Trados Studio) is the DQF project key (and possibly the DQF project ID, although I’m not sure what the difference between the two is).  Would it be possible to allow a project manager to create a project using the DQF web dashboard, as you do for non-Trados evaluations, and then have an option to display that project key (and ID if needed), so that the project manager could very easily copy that key and paste it into a project attribute in WorldServer?  This would allow us to run a very simple test:  I would create a DQF productivity project using the dashboard (do I need to specify the files when I do this, or with Trados projects, do I assume correctly that the file information is sent only when a translator starts working on a file?), get the project key, create a project in WorldServer and put the DQF project key in a project attribute (probably named “DQF”).  Then, when a translator downloads and opens the WorldServer project in Trados, the plugin (after you make a few changes to it) will access the DQF project attribute, get the project key, access the project in the DQF server, and begin to send productivity data as the translator works on each segment, just as happens now.  Does this make sense?

**Comment by achimr** [comment]
There is already an end point to get information on an existing project via HTTP GET to
/productivityProject/{projectid}
This returns info like this:
{"projectName":"Achim REST created project","process":2,"sourceLanguage":"en-US","contentType":1,"postEditingQuality":1,"industry":1}
This response does not include task information - which is tracked in issue #31 
Once this list would be available the tasks can be retrieved with HTTP GET requests to
/productivityProject/{projectid}/task/{taskid}
This needs to be permitted to be done by the project manager (tracked with issue #38)

Is this sufficient for this scenario?

**Comment by HenkBoxma** [comment]
I miss the MTEngine in the response

**Comment by achimr** [comment]
The MT engine is associated with the segments, so we would have to return an array of segments in the response to HTTP GET to /productivityProject/{projectid}/task/{taskid}/segment/ (issue TBD)

That said I'm not sure where the "MT Engine: " display for a task in the DQF UI comes from.

**Comment by achimr** [comment]
Henk to store MTEngine is Trados settings for now.

**Comment by HenkBoxma** [comment]
Fixed. The project currently stores mandatory:
1. Project KEY
2. Project ID
3. MT Engine

All other parameters are stored (optional). After the information is read from the sdlproj file, the information is requested at the server. This use case is necessary in case there is no internet connection.
