### ISSUE TITLE
Permit project manager to retrieve tasks associated with project created by him/her

### ISSUE THREAD

**Issue by achimr** [TAUSBV/dqf-api#38]
HTTP GET to /productivityProject/{projectid}/task/{taskid}
requires a translator key (DQF_TRANSLATOR_KEY), but it should also be authorized by project manager key that created the project (DQF_PMANAGER_KEY).

See also related issue #19

**Comment by nikosarg** [comment]
Duplicate or similar to #31

**Comment by achimr** [comment]
Certainly related to #31, but this one is about getting the task attributes and #31 is about getting a list of tasks.

**Comment by gorogattila** [comment]
JSON data including Task ID, translator name, email, language pair etc
