### ISSUE TITLE
Add end point to retrieve translator information

### ISSUE THREAD

**Issue by achimr** [TAUSBV/dqf-api#40]
HTTP GET to
/translator?email=joe@example.com
or 
/translator?name=Joe+Schmoe
or
/translator/{id}

Authorize with DQF_PMANAGER_KEY

Response: JSON structure with
* translator_id
* name
* email

When translator not found HTTP 404 status code response.

This can replace the existing GET request to /translator which doesn't seem to work.

**Comment by achimr** [comment]
Another option to retrieve the translator information should be added
HTTP GET to
/translator/
with the HTTP header DQF_TRANSLATOR_KEY

This should only return the information about this specific translator. Like this the translators can look up their own information. Prerequisite to fix #5

**Comment by nikosarg** [comment]
Will be reflected on the next update.
#5 has been scheduled for the DQF API v2.0 milestone. Shall we include it on the DQF API v1.0?

**Comment by achimr** [comment]
Thanks for adding this. On #5: I added a comment and moved it to v1.0.
