### ISSUE TITLE
Trados addin: auto detect MT engine when adding/updating a segment

### ISSUE THREAD

**Issue by HenkBoxma** [TAUSBV/dqf-api#41]
Currently, the user selects the MT at project creation and that one is used throughout the project. For each match, the engine should be selected. Hint: Patrick Hartnett could help us here.

**Comment by gorogattila** [comment]
What do we do with this?

**Comment by HenkBoxma** [comment]
Attila wrote:
I have worked with WordFast using multiple engines. I'm sure (cloud based) tools (including MateCat) also support the use of multiple engines.
Reason why MT engine is included in the Studio plug-in is because the segment origin information is not yet supported through the API. User can select this info manually at project creation but this is not the ideal scenario since our list is not complete. 
Happy to discuss further.
=================================
From: Steve Richardson <Stephen.Richardson@ldschurch.org>
Date: Wed, Aug 19, 2015 at 6:52 PM
Subject: RE: Question about WS workaround
To: Attila Görög <attila@taus.net>
Cc: Achim Ruopp <achim@taus.net>, Paola Valli <paola@taus.net>, Jaap van der Meer <jaap@taus.net>, Nikos Argyropoulos <nikos@taus.net>


I understand that you can use multiple engines with these tools.  You can also associate multiple MT engines with a project in Trados Studio, and the output from those engines, along with TM matches from possibly multiple TMs, are displayed in the Translation results window in Studio. (In my email below, when I said it would be difficult to switch between different engines, I assumed that you would want the output from only one at a time, or at least that one would be ordered in front of the other).  So if you intend to implement the tracking of segment origin information for different MT engines, are you also planning to do so for different TMs that are used with a project?  I guess I’m confused as to why you’re anticipating the use of different MT engines for segments but not the use of matches from different TMs for segments?  Be that as it may, I’d still strongly prefer to have the ability to specify a “default” MT engine for a project, since I think most enterprise customer who have trained MT systems for their content would only be using a single trained engine.
Thanks,
Steve

**Comment by gorogattila** [comment]
Settings: checkbox aanmaken - project basis vs segment basis (autodetect) - nog te bespreken met Nikos/Achim
Henk: investigate if engine can be detected per segment.

**Comment by pvalli** [comment]
This issue was moved to TAUSBV/dqf-for-Trados-Studio-plug-in#29
