### ISSUE TITLE
Create project via Dashboard (WORLDSERVER SUPPORT)

### ISSUE THREAD

**Issue by HenkBoxma** [TAUSBV/dqf-api#42]
We need the following:
1. Project manager creates a project in the dasboard, including all parameters.
2. The project KEY + ID will be shown.

Steve describes the following method to support Worldserver.

Would it be possible to allow a project manager to create a project using the DQF web dashboard, as you do for non-Trados evaluations, and then have an option to display that project key (and ID if needed), so that the project manager could very easily copy that key and paste it into a project attribute in WorldServer? 

 This would allow us to run a very simple test:  I would create a DQF productivity project using the dashboard (do I need to specify the files when I do this, or with Trados projects, do I assume correctly that the file information is sent only when a translator starts working on a file?), get the project key, create a project in WorldServer and put the DQF project key in a project attribute (probably named “DQF”).  Then, when a translator downloads and opens the WorldServer project in Trados, the plugin (after you make a few changes to it) will access the DQF project attribute, get the project key, access the project in the DQF server, and begin to send productivity data as the translator works on each segment, just as happens now.  Does this make sense?

**Comment by achimr** [comment]
Will document project and task creation through API test UI as a workaround.

**Comment by achimr** [comment]
Workaround:
You can use our test environment for the API to create an empty project and retrieve the project id and project key with the following steps:
* You need to get your project manager key for authorization as described here https://github.com/TAUSBV/dqf-api#obtaining-authorization-keys
* You can now create a project using the project manager key in the test environment: https://dqf.taus.net/assets/api/v1/index.html#!/productivityProject/POST_api_controllers_ProjectApiController_addProject
  * DQF_PMANAGER_KEY: the project manager key you just retrieved in 1.
  * name: a name you choose
  * quality_level: One of the values from here https://github.com/TAUSBV/dqf-api/wiki/Quality-Level-List-v0.9
  * process: One of the values from here https://github.com/TAUSBV/dqf-api/wiki/DQF-Process-List-v0.9
  * source_language: a combination of two-letter ISO 639-1 two letter language identifers+"-"+ISO 3166 country/region identifier (sorry, no BCP-47 here yet)
  * contentType: One of the values from here https://github.com/TAUSBV/dqf-api/wiki/Content-Type-List-v0.9
  * industry: One of the values from here https://github.com/TAUSBV/dqf-api/wiki/Industry-List-v0.9
* Once you submit by clicking the button "Try it" you should get a HTTP response with status code 200 if everything goes well
  * Important: write down/copy the "project_id" and "project_key" that you will receive in the headers!

This will create an empty project - you can see the project in your DQF project list with the status "Initializing".

**Comment by gorogattila** [comment]
No priority right now as we have started scoping out a possible integration with WorldServer.

**Comment by achimr** [comment]
As you say this won't be necessary when we have the DQF-WS add-in ready. Close?

BTW - the Worldserver workaround documentation on https://evaluate.taus.net/evaluate/api-integrators#taus-dqf-in-worldserver-workaround still does not document how to add the project id and project key information to a Worldserver project.

**Comment by pvalli** [comment]
I think it is not really relevant anymore for WS but it is still relevant for/ related to the user management in terms of user profile on the QD. Keep open or create a new thread for the non-WS case?

**Comment by pvalli** [comment]
This thread is still about a workaround to use DQF with WS without an official integration. This thread is now outdated. However in the future we may want to consider allowing users to create a project directly from the QD interface.
