### ISSUE TITLE
Server error when clicking on link of project without tasks

### ISSUE THREAD

**Issue by HenkBoxma** [TAUSBV/dqf-api#43]
If you open a project without tasks, the server shows an error.
1. Create a project
2. Then click on the link

![image](https://cloud.githubusercontent.com/assets/11646718/8166274/05b00cde-1397-11e5-86cb-ed7db47d4a2f.png)

**Comment by gorogattila** [comment]
The report is only available once the translator has sent the 1st segment. Until then NO report is available. We can display the following message:
"The report you are looking for has been initiated but no information can be displayed yet. Please, return to this page once the translator has started working on the project."

**Comment by gorogattila** [comment]
Checked and it's working fine.
