### ISSUE TITLE
Error when adding projects to DQF

### ISSUE THREAD

**Issue by ryanflee** [TAUSBV/dqf-api#46]
In version 0.98 of the plugin, I'm getting the following error when I try to add a new project to DQF:

![image](https://cloud.githubusercontent.com/assets/12663996/8218187/9e495f0a-14fe-11e5-8e44-d6fa287706b7.png)

The error appears after I click "Add to DQF" but before the DQF window pops up. It looks like the problem is in one of the combo boxes - here's a partial stack trace:

![image](https://cloud.githubusercontent.com/assets/12663996/8218232/eb41197e-14fe-11e5-8fed-c10676cd9e11.png)

As of right now, I can't add any projects to DQF.

**Comment by HenkBoxma** [comment]
This problem my be related to the other one. The issue is that it is not possible anymore to store metadata with segments. I assigned the taskID to the first segment. I will first work with SDL on the first issue and then see if this one also is resolved.

**Comment by ryanflee** [comment]
This seems to be fixed in v0.99 - I haven't been able to reproduce it since updating.

**Comment by HenkBoxma** [comment]
Cool!

-Henk Boxma.
