### ISSUE TITLE
Dashboard: project without tasks - nice message required when project initializing...

### ISSUE THREAD

**Issue by HenkBoxma** [TAUSBV/dqf-api#47]
Scenario:
1. Add project to DQF in Studio
(there are no tasks assigned yet)
2. Click the link in Studio
![image](https://cloud.githubusercontent.com/assets/11646718/8237217/fa17e51e-15ed-11e5-9402-e5d343f33e24.png)

Then you see this:
![image](https://cloud.githubusercontent.com/assets/11646718/8237203/e42c795e-15ed-11e5-9b33-7b6b2c5af2e7.png)

**Comment by gorogattila** [comment]
Hi Henk et al.
This message is a general message so not only for API or plug-in related problems. I think it's nice enough but not very specific if that's what you mean Henk. In the future we could add more specific messages to DQF but that's something we need to add to DQF. So I will close this issue now here and add it to Jira.

Attila
