### ISSUE TITLE
"Add to DQF" button not disabled when Trados opens in view other than Projects

### ISSUE THREAD

**Issue by ryanflee** [TAUSBV/dqf-api#48]
This one isn't critical, but on the other hand it should be an easy fix. When Trados Studio starts up, it remembers which view the user was in the last time the program was closed. If this view is not the Projects view, the "Add to DQF" button is not disabled for DQF projects.

![image](https://cloud.githubusercontent.com/assets/12663996/8241001/c88c96c2-15c3-11e5-9e1c-f92dd247206d.png)

Clicking the button just causes it to be disabled, so this is not a critical issue, just some quirky behavior.

To reproduce:

1. Create a new project in Trados Studio and add it to DQF (or use an existing project that has already been added to DQF).
2. Open the project, or navigate to one of the other views. The "Add to DQF" button is disabled.
3. Close Trados Studio.
4. Open Trados Studio again. You will be in the same view as before, but "Add to DQF" is now enabled, even though the project has already been added to DQF.

**Comment by HenkBoxma** [comment]
Fixed in 0.991
