### ISSUE TITLE
MT+PE+Human

### ISSUE THREAD

**Issue by gorogattila** [TAUSBV/dqf-api#49]
Achim Ruopp With v0.9 of the API this process cannot be supported - see https://github.com/TAUSBV/dqf-api/issues/13
Should this process even be offered in the API?
If yes, how can it be supported (CAT tool to decide which segments to be translated from scratch vs. post-edited?).
May 29 at 8:03pm • 
Achim Ruopp moved from DQF API Proposed Features for v2 to DQF API v1.0 (Evaluate).Jun 9
Achim Ruopp changed the due date to June 10.Jun 9
Attila Görög In a call a couple of weeks ago, Steve mentioned that the plug-in should block every second MT suggestion and pass an empty segment. Of course, first the empty segment issue should be solved in the API (there was a bug if I recall correctly)/
Jun 10 at 10:21am
Attila Görög Whether it's a priority, it's another question. There are users who see lots of benefit in this type of productivity measurement (John Tinsley) but I wouldn't say it's a top priority. MateCat could implement it right away, Studio could take longer. We should discuss with Alessandro and team/ Henk.

**Comment by nikosarg** [comment]
Somehow related to #75

**Comment by pvalli** [comment]
@DavidKoot & @HenkBoxma this thread should maybe answer the issue raised in: https://github.com/TAUSBV/dqf-api/issues/95#issuecomment-169712232

**Comment by DavidKoot** [comment]
MT+PE+Human is a process that is really DQF tools only. It the 'experimental' design in which you can try and measure human translation (from scratch) against machine translation. From a multilingual file, half of the segments you have to post-edit, and the other half you need to translate. You then get to see the differences in number in the report.
There is no equivalent in any other translation tool. If there is any human translation needed in a file done by machine translation, then the process would still be called "MT+PE". 
So, in the API, this 'MT+PE+Human' is not returned, and therefore cannot be selected when you have to choose the process.
