### ISSUE TITLE
Change email address

### ISSUE THREAD

**Issue by HenkBoxma** [TAUSBV/dqf-api#5]
Is it possible in the API for a translator to change the email address at a later moment in time?
Do we need an API where we can change the email address, if we provide the translatorKey as ID?

**Comment by achimr** [comment]
Attila: Should be able to track translator productivity longer term via same translator id (so email change should be possible)
Luis: Could add password verification for email address/name change
In project manager assignment of translators translators with a changed email address might lose out on work (if it goes to old email address)

**Comment by achimr** [comment]
Please add a an end point to the DQF API like this:
HTTP PUT
/translator/{translator_id}
Parameters:
name
email address
Authorization:
DQF_TRANSLATOR_KEY

Important: the DQF_TRANSLATOR_KEY has to correspond to the translator_id, i.e. a translator can only update his/her own info.
