### ISSUE TITLE
Unable offline in Trados plug-in

### ISSUE THREAD

**Issue by gorogattila** [TAUSBV/dqf-api#50]
Achim Ruopp Idea from Stephen Richardson: if the computer with SDL Trados Studio is not connected to the Internet, the DQF API plug-in could cache data (e.g. edited segments) and then submit them to the server once the machine connects back
May 29 at 7:43pm • 
Achim Ruopp assigned to you.May 29
Achim Ruopp I think this is probably not so easy to do and maybe less important than other features/fixes
May 29 at 7:44pm • 
Achim Ruopp Assigned to Attila to plan for v2 features.
May 29 at 7:44pm • 
Attila Görög Hi Achim. This is covered by Patricks Qualitivity plug-in, right? He is uploading the whole file at once. So adding a similar function would be double work. I'll added to version unknown for now.

**Comment by pvalli** [comment]
This issue was moved to TAUSBV/dqf-for-Trados-Studio-plug-in#28
