### ISSUE TITLE
Translators can only sign up for translator key/account via API

### ISSUE THREAD

**Issue by gorogattila** [TAUSBV/dqf-api#54]
Translators can only sign up for translator keys via the API right now. This means that we are relying on the API clients to provide the user interface to
* create translator accounts (key will be sent to translator email address)
* retrieve translator infomation (see https://github.com/TAUSBV/dqf-api/issues/40)
* update translator information (see https://github.com/TAUSBV/dqf-api/issues/5 )

We should consider whether we want to provide web UI in DQF to do this.

This one is related to ticket https://github.com/TAUSBV/dqf-api/issues/53.

**Comment by pvalli** [comment]
This is user- management related feature that has been imported in Asana: https://app.asana.com/0/78315545221439/81343959392943
