### ISSUE TITLE
Translator should receive email notification if added to project/task

### ISSUE THREAD

**Issue by gorogattila** [TAUSBV/dqf-api#56]
Translator should receive email notification if added to project/task.

**Comment by achimr** [comment]
Because the translator instructions are different for each different CAT tool notifying the translator should be the responsibility of the CAT tool. A web based CAT tool will notify a translator in a different way than an offline CAT tool.

**Comment by gorogattila** [comment]
Hi Achim,

You are right. Should be the responsibility of the CAT tool. Just like we
are sending an email when translators are added to the DQF database we
could easily send one when they are added to a DQF project. But then
probably they would get double emails. I will close this issue.


Quality Dashboard​
<https://events.taus.net/events/webinars/taus-quality-dashboard-webinar>
A GAME CHANGER FOR THE TRANSLATION INDUSTRY

Kind regards,

*Attila Görög*
Product Manager
*TAUS  <http://evaluate.taus.net/>*
*DQF <http://evaluate.taus.net/>*


*Email:* attila@taus.net

*Web:* www.taus.net

*Tel.:* +31 (0) 20 773 4172

*Skyp**e: *agg600


*NEW! TAUS Dynamic Quality Framework API
<https://dqf.taus.net/assets/api/v1/index.html>*
