### ISSUE TITLE
Typo in Implementation notes

### ISSUE THREAD

**Issue by gorogattila** [TAUSBV/dqf-api#58]
An already submitted translated segment can be updated. The time with be added to the segment already submitted. (should be "The time will be added...")

for the method update segment

**Comment by nikosarg** [comment]
Corrected!!

**Comment by achimr** [comment]
Resolved?

**Comment by gorogattila** [comment]
I think it is. But maybe it's good if Nikos sets all issues that are
resolved to resolved. Or do you want me to do that?


Quality Dashboard​
<https://events.taus.net/events/webinars/taus-quality-dashboard-webinar>
A GAME CHANGER FOR THE TRANSLATION INDUSTRY

Kind regards,

*Attila Görög*
Product Manager
*TAUS  <http://evaluate.taus.net/>*
*DQF <http://evaluate.taus.net/>*


*Email:* attila@taus.net

*Web:* www.taus.net

*Tel.:* +31 (0) 20 773 4172

*Skyp**e: *agg600


*NEW! TAUS Dynamic Quality Framework API
<https://dqf.taus.net/assets/api/v1/index.html>*


*New TAUS Review "The Innovation Issue" out now!
<https://www.taus.net/think-tank/taus-review>*
