### ISSUE TITLE
[ Enhancement ] API method to check the api_key

### ISSUE THREAD

**Issue by matecat** [TAUSBV/dqf-api#59]
I have to ask you for a little new feature if possible, we must call the DQF in an asyncronous way inside a queue service ( in the creation project phase basically ), so it would be a great advantage for us to have a method to check the goodness of the user provided api_key.

This way we can inform immediately the user that the provided key is invalid before that the project is created and before to tie the new project id to the DQF connector instance ( that would fail silently ).

Thank you in advance.

**Comment by nikosarg** [comment]
There is already a method to check the translator key: 
` /api/v1/translator/`
The translator gives his/her DQF_TRANSLATOR_KEY and if the key is valid, he/she gets a 200 response and the id, name and email.

A similar method has been implemented for the project managers:
` /api/v1/projectmanager/`
where the project manager can give the DQF_PMANAGER_KEY and if the key is valid, he/she gets a 200 response and the id, name and email.

The methods are currently available for testing on the [test](http://dqf.ta-us.net/) server.
Are these two methods enough for the functionality you describe? If yes, we could make them available on the production server with the v1.0 release.

**Comment by matecat** [comment]
Hi @nikosarg ,
yes, it's perfect for us. Thank You, we will try them. 
If possible, let us know when these features are available on the production environment.

**Comment by nikosarg** [comment]
Hi @matecat ,
That's great!! The DQF API v1.0, including these features, is already running on the [production environment](https://dqf.taus.net/assets/api/v1/index.html).
Thank you!
