### ISSUE TITLE
Company information is missing

### ISSUE THREAD

**Issue by nikosarg** [TAUSBV/dqf-api#6]
The company information is missing from the project creation level.

**Comment by gorogattila** [comment]
We are planning to give users the option to fill in the name of their customer/client in DQF UI. Right now we have a field in DQF called "Company Name" but this is ambiguous and not necessary because we have the user's company info (see explanation above).

**Comment by achimr** [comment]
Duplicate to https://github.com/TAUSBV/taus-dqf/issues/82
