### ISSUE TITLE
changing the default location on a next release of the plugin

### ISSUE THREAD

**Issue by gorogattila** [TAUSBV/dqf-api#61]
changing the default location on a next release of the plugin:
http://producthelp.sdl.com/kb/Articles/6124.html

C:\ProgramData\SDL\SDL Trados Studio\11\Plugins\
instead of
C:\Users\[user_name]\AppData\Local\SDL\SDL Trados Studio\11\Plugins\

**Comment by nikosarg** [comment]
Same with #60

**Comment by HenkBoxma** [comment]
Fixed

Kind regards,
Henk Boxma

_________________________________________________________________
*Boxma IT (*www.henkboxma.com)
office:      +31 (318) 78 6002
mobile:    +31 (6) 4913 1863
skype:      henk_boxma
address:   Burgemeester Prinslaan 3, 6711 KA  Ede, The Netherlands
_________________________________________________________________

**Comment by pvalli** [comment]
In which release of the plugin was this fixed? 1.1c? 
Could this be made more explicit for future issues please?  =]

**Comment by HenkBoxma** [comment]
This should have been fixed already. Try to run the installer.  Then you
will notice that the path points to program data.

Kind regards / mit freundlichen Grüßen / vriendelijke groet,
Henk Boxma
-- sent from mobile. Please excuse typos.

**Comment by pvalli** [comment]
Yes, Henk. It is fixed, thank you :) 
I was just trying to figure out/track in which release this happened. Do you recall this maybe? My guess would be 1.1c.

**Comment by HenkBoxma** [comment]
Hi Paola,
1.1.c was never released, so it must be 1.1.d.

Cheers from mega rainy Cornwall

Kind regards / mit freundlichen Grüßen / vriendelijke groet,
Henk Boxma
-- sent from mobile. Please excuse typos.
