### ISSUE TITLE
MateCat project not sent to DQF?

### ISSUE THREAD

**Issue by pvalli** [TAUSBV/dqf-api#66]
After creating and working on a project in MateCat I don't see the project created in my DQF account. (DQF PM Key was used and I was logged in in MateCat). 

![screen shot 2015-08-03 at 11 30 19](https://cloud.githubusercontent.com/assets/13329618/9034940/d732c6ae-39d3-11e5-9354-51f19c6e310a.png)
![screen shot 2015-08-03 at 11 29 19](https://cloud.githubusercontent.com/assets/13329618/9034941/d7344772-39d3-11e5-906c-3f82702a57b3.png)

**Comment by Ostico** [comment]
We raise an exeption on our side because of an HTTP 401 error on project creation call:

```
Exception received HTTP Code 401: [POST] 
https://dqf.taus.net/api/v1/productivityProject?name=Ansh_Anuwad&quality_level=2&process=3&source_language=en-US&contentType=9&industry=19

Response body: '{"code":401,"type":"unauthorized","message":"DQF_PMANAGER_KEY doesn\'t exist!"}'
```

Seems that our key was invalidated.

**Comment by gorogattila** [comment]
Hi Domenico. Can you be more specific. When do you get this error? What can we do?

**Comment by Ostico** [comment]
Hi @gorogattila ,

we solved in our side, one things lasts to implement, the check for the Project Manager key correctness before starting the project, there is an API available for that?

**Comment by nikosarg** [comment]
Hi @Ostico ,

There is an API available where you can pass the DQF_PMANAGER_KEY and get back the Project Manager details. See [here] (https://dqf.taus.net/assets/api/v1/index.html#!/projectmanager/GET_api_controllers_PMApiController_getProjectManagerInfo).

If the Project Manager doesn't exist you should see the following message:
"DQF_PMANAGER_KEY doesn't exist or it doesn't belong to a Project Manager!"

**Comment by gorogattila** [comment]
And this is a good verification of the PM key.
If the PM key is fake, it can't give you back any PM details so you get an
error.
Is that correct Nikos?



TAUS Annual Conference
<https://events.taus.net/events/conferences/taus-annual-conference-2015>, 12-13
October, San Jose, CA (USA)

*“Translation innovation: leading the change” *

*Contend for the Innovation Excellence Award
<https://events.taus.net/events/conferences/taus-annual-conference-2015#excellence-awards>*

TAUS QE Summit at eBay
<https://events.taus.net/events/forums/taus-qe-summit-san-jose-2015>, 14
October*, *San Jose, CA (USA)

Kind regards,

*Attila Görög*
Product Manager
*TAUS  <http://evaluate.taus.net/>*
*DQF <http://evaluate.taus.net/>*


*Email:* attila@taus.net

*Web:* www.taus.net

*Tel.:* +31 (0) 20 773 4172

*Skyp**e: *agg600


Quality Dashboard​
<https://events.taus.net/events/webinars/taus-quality-dashboard-webinar>
A GAME CHANGER FOR THE TRANSLATION INDUSTRY
