### ISSUE TITLE
Link to DQF in MateCat

### ISSUE THREAD

**Issue by pvalli** [TAUSBV/dqf-api#67]
The link to DQF provided in the Editing Log page redirects to the DQF log-in page. 
Can the link be made project-specific and/or can the link redirect to the report page in DQF instead of the login page? (https://dqf.taus.net/reports)

**Comment by Ostico** [comment]
Can you provide me an example on how we must format the url to point to the right report?

Tnx

**Comment by gorogattila** [comment]
https://dqf.taus.net/reports/{PROJECT ID}

For example the report url of project with project id 2088 is:

https://dqf.taus.net/reports/2088
