### ISSUE TITLE
Plugin version for SDL Trados Studio 2015

### ISSUE THREAD

**Issue by pvalli** [TAUSBV/dqf-api#68]
Please correct the plugin version in Studio 2015. It should be 1.1 not 1.1d.

![studio_2015_version](https://cloud.githubusercontent.com/assets/13329618/9035165/bd9da072-39d5-11e5-8a86-250f54ab4792.png)

**Comment by gorogattila** [comment]
1.1.4

**Comment by HenkBoxma** [comment]
Moved version and plugin information to the bottom/right
Added the build date after the version number: version 1.1 (3 SEP 2015)
Added scrollbars so that preview is always visible
![image](https://cloud.githubusercontent.com/assets/11646718/9653652/39e37e56-5225-11e5-82a6-79c303bf5c1f.png)

**Comment by HenkBoxma** [comment]
Please test

**Comment by pvalli** [comment]
If the file-name + path is super long it's kinda packed but as it does not overlap with the studio version info I'd say it's fine like this.

![image](https://cloud.githubusercontent.com/assets/13329618/9905445/5e6f88a4-5c85-11e5-9172-fb129c8d7d61.png)
