### ISSUE TITLE
Error message in Studio "Object reference not set" - Please investigate problem source

### ISSUE THREAD

**Issue by pvalli** [TAUSBV/dqf-api#70]
When clicking on ADD TO DQF both in the Trados Tab and from the ribbon, the user gets an error message (see screenshot). The message does not appear if ADD to DQF is selected from the contextual menu (right click on project name).

![studio_error_message](https://cloud.githubusercontent.com/assets/13329618/9221873/c6785754-40ed-11e5-831a-377253cda491.jpg)

Here is the SDL Error log:
****
<SDLErrorDetails time="8/12/2015 11:53:08 AM">
  <ErrorMessage>Object reference not set to an instance of an object.</ErrorMessage>
  <Exception>
    <Type>System.NullReferenceException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</Type>
    <HelpLink />
    <Source>Dqf</Source>
    <HResult>-2147467261</HResult>
    <StackTrace><![CDATA[   at Dqf.MyProjectViewPartControl.btnAddToDqf_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)]]></StackTrace>
  </Exception>
  <Environment>
    <ProductName>SDL Trados Studio</ProductName>
    <ProductVersion>11.0.0.0</ProductVersion>
    <EntryAssemblyFileVersion>11.2.4409.10</EntryAssemblyFileVersion>
    <OperatingSystem>Microsoft Windows 7 Enterprise </OperatingSystem>
    <ServicePack>Service Pack 1</ServicePack>
    <OperatingSystemLanguage>1033</OperatingSystemLanguage>
    <CodePage>1252</CodePage>
    <LoggedOnUser>EMEA\FRRI</LoggedOnUser>
    <DotNetFrameWork>4.0.30319.18444</DotNetFrameWork>
    <ComputerName>FRRI3</ComputerName>
    <ConnectedToNetwork>True</ConnectedToNetwork>
    <PhysicalMemory>8265200 MB</PhysicalMemory>
  </Environment>
</SDLErrorDetails>
***

**Comment by HenkBoxma** [comment]
Is is reproducable?

**Comment by HenkBoxma** [comment]
There was a problem when adding projects when there was no project activated in Studio (i.e. marked as bold).
When that was not the case, and you added the project to DQF, it was actually added, but the view in Studio was not updated.
Fixed it.

**Comment by HenkBoxma** [comment]
@pvalli : please test

**Comment by pvalli** [comment]
I am not sure whether #2 and #80 have solved this. We cannot reproduce the error internally. Will try to get another test with this user to see if has improved.

**Comment by pvalli** [comment]
With the new plugin this error did not appear. I would consider this solved for now.
