### ISSUE TITLE
File path mismatch in Studio

### ISSUE THREAD

**Issue by pvalli** [TAUSBV/dqf-api#71]
Background info: a project has been created/opened in Studio and has been added to DQF.
Issue:  The same package was reimported in Studio (after changing the unpack location AND removing the project from the project list in Studio) to run another test. When the project is listed, the plugin retrieves the DQF project settings from the previous project (see differing file paths in the screenshot). 
Why is this happening? 
Thanks for clarifying.

![screen shot 2015-08-12 at 13 17 19](https://cloud.githubusercontent.com/assets/13329618/9222741/88b5c29c-40f4-11e5-994a-63362bab3ff3.png)

**Comment by HenkBoxma** [comment]
The picture is blurry. Can you please write the full path that is shown in the list and the full path that is shown in "Current Project".
The paths look the same. You can make the Location-column wider.

**Comment by pvalli** [comment]
Sure Henk. Here are the paths:

C:\Users\FRRI\Documents\Studio 2014\Projects\demo2
(this is the one we tried to reimport live)

C:\Users\FRRI\Documents\Studio 2014\Projects\test e2e\Test DQF Bis_en-US_fr-FR_20150811.131613.sdlproj
(this was the project previously added to DQF)

Project name "Test DQF Bis_en-US_fr-FR_20150811.131613"
Project folders are "DEMO2" and "TEST e2e"

**Comment by HenkBoxma** [comment]
@pvalli: can you please retest it?

**Comment by pvalli** [comment]
We cannot reproduce the error internally. Will try to get another test with this user to see if has improved.

**Comment by pvalli** [comment]
This issue was moved to TAUSBV/dqf-for-Trados-Studio-plug-in#27
