### ISSUE TITLE
Display of MT engines list

### ISSUE THREAD

**Issue by pvalli** [TAUSBV/dqf-api#72]
The latest MT additions are displayed at the bottom of the list. 
Can they be sorted alphabetically instead of by ID?

![mt_list](https://cloud.githubusercontent.com/assets/13329618/9305408/8769d9a4-44f1-11e5-9280-7a04aa3c0d79.jpeg)

**Comment by gorogattila** [comment]
Nikos to sort it in a way that order in the returned JSON object is alphabetical. Exception is "other" (ID 40); that should be always at the end of the list

**Comment by pvalli** [comment]
Engines are displayed alphabetically now. OTHER, however, is not at the bottom of the list. @nikosarg can this be fixed?

**Comment by nikosarg** [comment]
It's fixed. Other will be shown at the bottom of the list!

**Comment by pvalli** [comment]
Ok if you tested it, please close this issue and also complete the task in Asana. 
I guess now @HenkBoxma will need to update his MT engine list in the plugin.

**Comment by HenkBoxma** [comment]
The plugin gets the list from the DQF server and displays it as-is. Therefore, there is no need to adapt the plugin. "Other" is not at the end. The server returns the following JSON object:

[{"id":1,"name":"<none>","archive":0},{"id":2,"name":"Apertium","archive":0},{"id":3,"name":"Apertium-Moses Hybrid","archive":0},{"id":4,"name":"Asia Online","archive":0},{"id":5,"name":"Bing Translator","archive":0},{"id":6,"name":"Capita MT","archive":0},{"id":7,"name":"Carabao MT","archive":0},{"id":8,"name":"CCID Translation Platform","archive":0},{"id":9,"name":"CrossLang","archive":0},{"id":10,"name":"East Linden","archive":0},{"id":11,"name":"Firma8","archive":0},{"id":12,"name":"FreeT","archive":0},{"id":13,"name":"Google Translate","archive":0},{"id":14,"name":"Iconic","archive":0},{"id":15,"name":"KantanMT","archive":0},{"id":16,"name":"Kodensha","archive":0},{"id":17,"name":"LDS Translator","archive":0},{"id":18,"name":"Linguasys","archive":0},{"id":19,"name":"Lucy Software","archive":0},{"id":20,"name":"Microsoft Translator Hub","archive":0},{"id":21,"name":"Moses","archive":0},{"id":22,"name":"MyMemory","archive":0},{"id":23,"name":"myMT","archive":0},{"id":24,"name":"Opentrad","archive":0},**{"id":40,"name":"Other","archive":0}**,{"id":25,"name":"PangeaMT","archive":0},{"id":26,"name":"Pragma","archive":0},{"id":27,"name":"PROMT","archive":0},{"id":28,"name":"Reverso","archive":0},{"id":29,"name":"Safaba","archive":0},{"id":30,"name":"SDL BeGlobal","archive":0},{"id":41,"name":"SDL Language Cloud","archive":0},{"id":31,"name":"Sovee","archive":0},{"id":32,"name":"Systran","archive":0},{"id":33,"name":"T-Text","archive":0},{"id":34,"name":"Tauyou","archive":0},{"id":35,"name":"Toshiba","archive":0},{"id":36,"name":"TransSphere","archive":0},{"id":37,"name":"Weblio","archive":0},{"id":38,"name":"WebTrance","archive":0},{"id":39,"name":"weMT","archive":0}]

**Comment by nikosarg** [comment]
The change will take effect from the next release!
