### ISSUE TITLE
Change default value in DQF settings 

### ISSUE THREAD

**Issue by pvalli** [TAUSBV/dqf-api#74]
Please change the default value in the DQF dropdown settings from the existing ones (see screenshot) in "< Please select >" for all fields (all required). 
Ideally, if a field is not properly set, users should get a warning message.

![default_settings](https://cloud.githubusercontent.com/assets/13329618/9305584/c2ba87e6-44f2-11e5-9d03-9fad1ebd5439.png)

**Comment by HenkBoxma** [comment]
Easy to implement

**Comment by HenkBoxma** [comment]
Fixed.
@pvalli: please test. 

![image](https://cloud.githubusercontent.com/assets/11646718/9721387/e4c407c4-5599-11e5-8909-7f85961f807f.png)

**Comment by pvalli** [comment]
Works, thanks!
