### ISSUE TITLE
Add api_supported field to DQF processes

### ISSUE THREAD

**Issue by achimr** [TAUSBV/dqf-api#75]
Add api_supported field in response to /process/ end point. Type: Integer (1/0) as we already use this as boolean (and 0 evaluates as false in Javascript; see http://james.padolsey.com/javascript/truthy-falsey/)

Return 1 for all process types, except "MT+PE+Human" 
Return 0 for process type "MT+PE+Human"

**Comment by nikosarg** [comment]
The api_supported field has been added to the [/process/] (http://dqf.ta-us.net/assets/api/v1/index.html#!/process/GET_api_controllers_ProcessApiController_getProcess) end point. The new field has been implemented only in the java code and a new attribute has not been introduced in the database.
