### ISSUE TITLE
DQF project creation API endpoint does not do a complete check of the source language

### ISSUE THREAD

**Issue by liemily** [TAUSBV/dqf-api#77]
If the source language "en", without the country specification, is given, the DQF API will still create the project successfully. However, the source language is not set correctly and the user would not know until s/he views this project's creation screen on the DQF site.

**Comment by nikosarg** [comment]
In this case the source language will be set as "Source Language: English ()". That's because the two letter country identifier has not been specified.
Is this the required behaviour or shall we block requests that don't contain the country identifier?

**Comment by liemily** [comment]
On the actual DQF project creation page, the project with source language "en" shows "--Select Source Language--" because "English ()" is not an option in the drop-down. This is confusing from a user standpoint. I think it would be better to block requests like that.

**Comment by achimr** [comment]
Discussed this with Nikos. In principle we could support DQF projects that have source/target languages that have a language identifier without a country. There are some smaller issues like the one Emily describes above. We are also not familiar with the DQF history of supporting only language& country combinations up to now.

**Comment by gorogattila** [comment]
Only language without country code will be rejected. In a later phase we will see how these language codes can be mapped to our language-country code.

**Comment by pvalli** [comment]
@nikosarg has this been implemented? Could you pls update about the status? Thanks!

**Comment by nikosarg** [comment]
As Attila mentioned at last, only language without country code will be rejected.

**Comment by pvalli** [comment]
Does that mean that we do accept locales (es-co) that we currently do not have in the database? 
And that locales will still be accepted even if not existing (es-xy)?
What does "our language-country code" exactly mean? There are ISO standards for country codes (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes.)

**Comment by nikosarg** [comment]
Yes, (es-co) will be added with the name "Spanish (Colombia)" and the (es-xy) won't be accepted. If (es-co) is not in our database it will be added as archived in the beginning until we manually make it active. 

I guess when Attila says "our language-country code" he means that we currently accept the use of (two letter language id)-(two letter country identifier) combination. Validity of the id's (ISO 639-1 and ISO 3166 two-letter identifiers). So, not just an ISO 639-1: two-letter code.

Same conditions apply both on Source and Targer languages.
