### ISSUE TITLE
Wrong Project KEY for a DQF project

### ISSUE THREAD

**Issue by pvalli** [TAUSBV/dqf-api#79]
A DQF project cannot be processed due to a new error to us. 
Nikos investigated and found out the following: 
from the screenshots I can see that he is trying to create a task for the project with id 2070
the PROJECT_KEY seems to be wrong
the project 2070 has the PROJECT_KEY: 6gg69gb1up1u8o2sghah3p5gc0uqanm4lv67qk4bj38rdfogdvjq

Can you explain how/why this can happen? Thanks.

![image](https://cloud.githubusercontent.com/assets/13329618/9517118/c3be153c-4cad-11e5-989a-ba6451458d78.png)

![image](https://cloud.githubusercontent.com/assets/13329618/9517122/d01c8ae8-4cad-11e5-8bf5-bf4fefed1974.png)

**Comment by HenkBoxma** [comment]
@pvalli: please test it. Should be clearer now the following issues are solved: #2 #86

**Comment by pvalli** [comment]
We cannot reproduce the error internally. Will try to get another test with this user to see if has improved.

**Comment by pvalli** [comment]
This issue was moved to TAUSBV/dqf-for-Trados-Studio-plug-in#38
