### ISSUE TITLE
Edit error message in plugin

### ISSUE THREAD

**Issue by pvalli** [TAUSBV/dqf-api#80]
HINT in Error Message 
"The DQF server could not process the request. Hint: Check your DQF credentials" 
is confusing for users if the issue is in fact not related to their credentials. 

Enhancement suggestions:
- Remove hint
- Make the hint more general e.g. "Please send a screenshot to DQF support"
- Customize error messages based on information from API (e.g. Hint: Check your (company's) Firewall settings)

![image](https://cloud.githubusercontent.com/assets/13329618/9517728/3f95935c-4cb2-11e5-9479-e89918669783.png)

**Comment by HenkBoxma** [comment]
Should be better now. Improved the error message and put all info in one text box (#2). My feeling is that this issue is solved with #70. 

@pvalli : please test

**Comment by pvalli** [comment]
Tested for #2. Works.
