### ISSUE TITLE
Translators do not see project settings

### ISSUE THREAD

**Issue by HenkBoxma** [TAUSBV/dqf-api#84]
Is this a bug?

1 Translator gets a project from PM (Worldserver)
2. Translator open project and get the following message:

![image](https://cloud.githubusercontent.com/assets/11646718/9576438/00c534d8-4fd8-11e5-844a-f61ab48c8ed6.png)

**Comment by HenkBoxma** [comment]
I do not get the error when I select this package:

![image](https://cloud.githubusercontent.com/assets/11646718/9681186/67cbbefa-52fc-11e5-90f0-6065ce25de6b.png)

I get the following error when I open the editor:
![image](https://cloud.githubusercontent.com/assets/11646718/9681207/9200512c-52fc-11e5-9f64-bdbd7d6b016d.png)

**Comment by HenkBoxma** [comment]
This project is on the test server.

**Comment by HenkBoxma** [comment]
@nikosarg 

Hi Nikos,
There is no error shown anymore when you select a project that was created with worldserver. The only think that you see is the following:

![image](https://cloud.githubusercontent.com/assets/11646718/9689480/96227976-5336-11e5-8812-4a1c7c7cd428.png)

When I click the Project Settings button, then I get the error message:
![image](https://cloud.githubusercontent.com/assets/11646718/9689489/a861ace2-5336-11e5-940c-7650466d9d54.png)

When I look at the API, the method to retrieve the project data requires a PM key.

Attila told me that this is not needed anymore. Can you please provide more input?

**Comment by nikosarg** [comment]
Hi @HenkBoxma ,

Translators can retrieve the Project data only for projects they are assigned in.
Please check this [method] (https://dqf.taus.net/assets/api/v1/index.html#!/productivityProject/GET_api_controllers_ProjectApiController_findProjectById).

**Comment by pvalli** [comment]
Now we can see the project settings without the warning. Issue solved?

**Comment by HenkBoxma** [comment]
If you cannot reproduce the error anymore, then we can close this issue
