### ISSUE TITLE
Project attributes to be received by sending translator key and Project ID

### ISSUE THREAD

**Issue by gorogattila** [TAUSBV/dqf-api#85]
https://dqf.taus.net/assets/api/v1/index.html#!/productivityProject/GET_api_controllers_ProjectApiController_findProjectById

**Comment by HenkBoxma** [comment]
![image](https://cloud.githubusercontent.com/assets/11646718/9692410/3285e91c-5349-11e5-91d1-14e61a0acd9d.png)

**Comment by HenkBoxma** [comment]
@pvalli : please retest.

I get an access not permitted (403) error when I invoke the operation with the DQF_PMANAGER_KEY. Could be that I am using the wrong server. 
![image](https://cloud.githubusercontent.com/assets/11646718/9720933/a3c8041a-5593-11e5-8c4a-a68fe5c6bc4f.png)

**Comment by pvalli** [comment]
Project Settings are displayed but Project ID link is greyed out when after removing PM key.
