### ISSUE TITLE
Configure DQF server for testing purposes

### ISSUE THREAD

**Issue by HenkBoxma** [TAUSBV/dqf-api#86]
The server connects to dqf.taus.net. The test server is at dqf.ta-us.net.
It should be possible to overwrite the following settings:
1. URL to DQF

If the URL is set to a different server, then the plugin will also use different keys for the translator and the PM. Those keys are not editable via the plugin.:
2. Translator key for test server
3. PM key for test server

Idea: create file in appdata that overrides settings. The plugin will detect if that file exists. If so, then it will offer a checkbox, so that the other settings can be overridden.

**Comment by HenkBoxma** [comment]
Added an easter egg. Open the credentials:

![image](https://cloud.githubusercontent.com/assets/11646718/9678730/9e7fb2da-52e8-11e5-8914-5755b8e60e7c.png)

If you double click the bottom left of the credentials screen the debug settings appear:

![image](https://cloud.githubusercontent.com/assets/11646718/9678746/bdcdb6c8-52e8-11e5-9ced-3c273c73228f.png)


Enable. The test-server fields are marked as yellow, and a message is shown.

![image](https://cloud.githubusercontent.com/assets/11646718/9678763/dad8c866-52e8-11e5-913c-19cfa9b95f22.png)

You can now enter the credentials for the test server.
Uncheck the checkbox to see the normal settings again.

![image](https://cloud.githubusercontent.com/assets/11646718/9678789/13250676-52e9-11e5-9fb2-0b0fa86e8086.png)

**Comment by HenkBoxma** [comment]
Please test with new version 1.1

**Comment by pvalli** [comment]
Nice easter egg! :)
Works!
