### ISSUE TITLE
Translators registry should directly return translator key.

### ISSUE THREAD

**Issue by NunoXu** [TAUSBV/dqf-api#87]
The only way right now to obtain the translator key is through the confirmation e-mail.
This is not practical if the translators are users of the integrated platform, but are not direct users of the DQF platform.

There should be a way of directly fetching the translator key. Maybe through the POST /translator endpoint?

**Comment by gorogattila** [comment]
I suggest you use this POST/translator endpoint to send us an email address. Once we have the email-address we can generate the Translator key for that unique email address and send it through email. This is also the way how we implemented it in the plug-in for Trados Studio.

**Comment by pvalli** [comment]
@vinodMS FYI for your scoping
