### ISSUE TITLE
when translating from scratch New target is copied to MT target

### ISSUE THREAD

**Issue by gorogattila** [TAUSBV/dqf-api#88]
This might be an issue for the SDL trados plug-in or DQF. See attached report from DQF productivity report. No MT engine suggestion has been used. All segments were translated from scratch. Still the column of the MT output is filled in with the translated segments instead of left empty.
<img width="1238" alt="screen shot 2015-09-02 at 4 53 11 pm" src="https://cloud.githubusercontent.com/assets/12510338/9634679/2a0849d6-5193-11e5-9538-41ea5fc0c394.png">

Question is what the plug-in sends when the target is empty?

**Comment by pvalli** [comment]
Scenario: 
1. Select a segment 
2. Immediately start translating (no input from MT) from scratch
3. MT output should be empty
4. Edit distance should be calculated only on "post-edited" (our chart should be on the 0 in this case)

**Comment by pvalli** [comment]
This issue was moved to TAUSBV/dqf-for-Trados-Studio-plug-in#26
