### ISSUE TITLE
Panel view not initialized 

### ISSUE THREAD

**Issue by HenkBoxma** [TAUSBV/dqf-api#89]
Open Studio (where the DQF panel is not selected):
![image](https://cloud.githubusercontent.com/assets/11646718/9654102/a574082c-5228-11e5-9f4d-77a6afd2d6b9.png)

Select the TAUS DQF tab:
![image](https://cloud.githubusercontent.com/assets/11646718/9654112/cc604b08-5228-11e5-81e8-8410bd3b54e9.png)

The project name is not shown. 
It will be shown after you select another project name and then go back
![image](https://cloud.githubusercontent.com/assets/11646718/9654120/da605a4a-5228-11e5-9f6b-52278e4b5c8c.png)

**Comment by HenkBoxma** [comment]
@pvalli: Please test.

**Comment by pvalli** [comment]
I can see the project attributes right away. No need to switch between projects.
