### ISSUE TITLE
DQF settings not propagated to package

### ISSUE THREAD

**Issue by HenkBoxma** [TAUSBV/dqf-api#91]
Hi Henk, 

I am writing here for a change as I have some additional material this time. We may want to have this content in Github at some point for our reference.

We have tried to test the new version for the old issues which were still open. I closed a couple based on what we could test. We need your help to figure out the open issue though.

We could do every step without any of the old issues (e.g. object reference not set etc). The project was created in DQF etc. When creating a project package though, the DQF settings are not transferred to the package, which is sent to me as "add to DQF". This was the main problem last time too but we thought it was for the earlier problems at project creation. I demoed the same procedure and it worked fine on my end.

Here's additional info you should have:

- The new plugin was installed but a warning appeared that it may have not been installed properly. Unfortunately I don't have a screenshot or have seen it myself but we proceeded anyway. 

- The project which was opened in Studio comes from TMS (*.stppk). I think I used the very same file and had no issues with my Trados.

- Studio SP2 still needed to be installed.

>> Do you have any idea what this can be? How can it be fixed?

Hope my info helps. Please let me know if you need anything else.

Thanks!

Paola

**Comment by HenkBoxma** [comment]
I cannot reproduce this error. Here is what I did.

1. Create a new project
2. Add package to DQF
3. Export package
4. DQF settings are visible

Can you please send me an stppk-file?



Kind regards,
Henk Boxma

**Comment by HenkBoxma** [comment]
@pvalli :please send me an stppk-file

**Comment by pvalli** [comment]
This issue was moved to TAUSBV/dqf-for-Trados-Studio-plug-in#39
