### ISSUE TITLE
Add Unbabel to CAT tools

### ISSUE THREAD

**Issue by gorogattila** [TAUSBV/dqf-api#93]
Not really a CAT tool but Lingotek is also added so let's add Unbabel.

**Comment by pvalli** [comment]
To avoid potential "labeling" issues with integrators could we consider renaming "CAT tool" into something more general? Like "translation platform" or "technology" vs "MT engine"?

**Comment by pvalli** [comment]
This issue was moved to TAUSBV/taus-dqf#174
