### ISSUE TITLE
More verbose error messages

### ISSUE THREAD

**Issue by DavidKoot** [TAUSBV/dqf-api#98]
Would it be possible to have more explanation added to the error codes? So, when the translator key is wrong, instead of 'Access is not permitted', it returns something like 'Translator key not valid for this project'. If a plugin then passes these messages to the user, they probably won't ask so much for support, and will find it easier to use.

**Comment by pvalli** [comment]
Feature request. Moved to Asana: https://app.asana.com/0/79118627885934/81343959392925
